name: toolbox
version: "0.1.8"
summary: set of usefull shell tools
description: |
 set of usefull shell tools

confinement: strict
grade: devel

apps:
    nano:
        command: nano
        plugs: &default [home, process-control, system-observe, mount-observe,hardware-observe,framebuffer, network-control, physical-memory-control, raw-usb, removable-media, system-trace, uhid ]

    wget:
        command: wget
        plugs: *default

    ag:
        command: ag
        plugs: *default

    mc:
        command: mc
        plugs: *default

    mcdiff:
        command: mcdiff
        plugs: *default

    mcedit:
        command: mcedit
        plugs: *default

    mcview:
        command: mcview
        plugs: *default

    pastebinit:
        command: pastebinit
        plugs: *default

    curl:
        command: curl
        plugs: *default

    lsusb:
        command: lsusb
        plugs: *default

    usb-devices:
        command: usb-devices
        plugs: *default

    usbhid-dump:
        command: usbhid-dump
        plugs: *default

    cppfilt:
        command: c++filt
        plugs: *default

    elfedit:
        command: elfedit
        plugs: *default

    readelf:
        command: readelf
        plugs: *default

    ld:
        command: ld
        plugs: *default

    ld-bfd:
        command: ld.bfd
        plugs: *default

    strings:
        command: strings
        plugs: *default

    size:
        command: size
        plugs: *default

    strip:
        command: strip
        plugs: *default

    objcopy:
        command: objcopy
        plugs: *default

    objdump:
        command: objdump
        plugs: *default

    addr2line:
        command: addr2line
        plugs: *default

    dwp:
        command: dwp
        plugs: *default

    as:
        command: as
        plugs: *default

    ar:
        command: ar
        plugs: *default

    gold:
        command: gold
        plugs: *default

    ld-gold:
        command: ld.gold
        plugs: *default

    nm:
        command: nm
        plugs: *default

    gprof:
        command: gprof
        plugs: *default

    ranlib:
        command: ranlib
        plugs: *default

    set-path:
        command: bin/set-path
        plugs: *default

    screen:
        command: screen
        plugs: *default

    tree:
        command: tree
        plugs: *default

    zip:
        command: zip
        plugs: *default

    unzip:
        command: unzip
        plugs: *default

    vim:
        command: vim.basic
        plugs: *default

    vim-tiny:
        command: vim.tiny
        plugs: *default

    vimdiff:
        command: vim.basic -d
        plugs: *default

    lsof:
        command: lsof
        plugs: *default

    iotop:
        command: iotop
        plugs: *default

    hdparm:
        command: hdparm
        plugs: *default

    rhash:
        command: rhash
        plugs: *default

    gost-hash:
        command: gost-hash
        plugs: *default

    has160-hash:
        command: has160-hash
        plugs: *default

    sfv-hash:
        command: sfv-hash
        plugs: *default

    tiger-hash:
        command: tiger-hash
        plugs: *default

    tth-hash:
        command: tth-hash
        plugs: *default

    whirlpool-hash:
        command: whirlpool-hash
        plugs: *default

    clean-journalctl:
        command: journalctl --vacuum-time=1seconds
        plugs: *default

    ethtool:
        command: sbin/ethtool
        plugs: *default

    i2cset:
        command: usr/sbin/i2cset
        plugs: *default

    i2cdump:
        command: usr/sbin/i2cdump
        plugs: *default

    i2cdetect:
        command: usr/sbin/i2cdetect
        plugs: *default

    i2cget:
        command: usr/sbin/i2cget
        plugs: *default

    cryptsetup:
        command: sbin/cryptsetup
        plugs: *default

    veritysetup:
        command: sbin/veritysetup
        plugs: *default

    cryptsetup-reencrypt:
        command: sbin/cryptsetup-reencrypt
        plugs: *default

    luksformat:
        command: usr/sbin/luksformat
        plugs: *default

    dmsetup:
        command: sbin/dmsetup
        plugs: *default

    convert-dtsv0:
        command: usr/bin/convert-dtsv0
        plugs: *default

    dtdiff:
        command: usr/bin/dtdiff
        plugs:
            - home

    fdtput:
        command: usr/bin/fdtput
        plugs:
            - home

    dtc:
        command: usr/bin/dtc
        plugs:
            - hardware-observe
            - home

    fdtdump:
        command: usr/bin/fdtdump
        plugs:
            - home

    fdtget:
        command: usr/bin/fdtget
        plugs:
            - home

    strace:
        command: usr/bin/strace
        plugs:
            - log-observe

    rsync:
        command: usr/bin/rsync
        plugs:
            - home
            - removable-media
            - optical-drive

    iperf3:
        command: usr/bin/iperf3
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    netstat:
        command: bin/netstat
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    arp:
        command: usr/sbin/arp
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe
    nameif:
        command: sbin/nameif
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    ipmaddr:
        command: sbin/ipmaddr
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    plipconfig:
        command: sbin/plipconfig
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    ifconfig:
        command: sbin/ifconfig
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    route:
        command: sbin/route
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    mii-tool:
        command: sbin/mii-tool
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    iptunnel:
        command: sbin/iptunnel
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    rarp:
        command: sbin/rarp
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

    slattach:
        command: sbin/slattach
        plugs:
            - home
            - network
            - network-bind
            - network-control
            - network-observe
            - network-setup-control
            - network-setup-observe

parts:
    tools:
        source: scripts
        plugin: dump
        stage-packages:
          - wget
          - nano
          - silversearcher-ag
          - pastebinit
          - curl
          - binutils
          - screen
          - tree
          - zip
          - unzip
          - vim
          - vim-tiny
          - vim-common
          - vim-runtime
          - lsof
          - iotop
          - hdparm
          - rhash
          - ethtool
          - i2c-tools
          - cryptsetup-bin
          - libgpm2
          - dmsetup
          - device-tree-compiler
          - strace
          - rsync
          - iperf3
          - net-tools
        filesets:
          fat:
            - -usr/lib/gcc
            - -usr/share/vim
        stage:
            - $fat
        prime:
            - $fat

    mc:
        source: https://github.com/MidnightCommander/mc.git
        plugin: autotools
        configflags:
            - --prefix=/snap/toolbox/current/usr 
            - --sysconfdir=/var/snap/toolbox/common/etc
            - --without-x
        build-packages:
            - libglib2.0-dev
            - libslang2-dev
            - gettext
        override-build: |
            snapcraftctl build
            mv $SNAPCRAFT_PART_INSTALL/snap/toolbox/current/usr $SNAPCRAFT_PART_INSTALL/
            rm -rf $SNAPCRAFT_PART_INSTALL/snap
            mv $SNAPCRAFT_PART_INSTALL/var/snap/toolbox/common/etc $SNAPCRAFT_PART_INSTALL/
            rm -rf $SNAPCRAFT_PART_INSTALL/var

    usbutils:
        source: https://github.com/gregkh/usbutils.git
        plugin: autotools
        build-packages:
            - libusb-1.0-0-dev
            - zlib1g
            - gawk
            - pkg-config
            - libudev-dev
        stage-packages: [libusb-1.0-0]
        configflags:
            - --prefix=/usr
            - --libdir=/usr/lib
            - --localstatedir=/var/snap/toolbox/common/
        override-pull: |
            snapcraftctl pull
            git submodule init
            git submodule update
            autoreconf --install --symlink
