name: toolbox
version: "0.3.1"
summary: set of usefull shell tools
description: |
 set of usefull shell tools

confinement: strict
grade: stable

apps:
    help:
        command: bin/toolbox-help
        adapter: none

    nano:
        command: nano
        plugs: &default-storage [home, removable-media]

    wget:
        command: wget
        plugs: &default-storage-net [home, removable-media, network]

    ag:
        command: ag
        plugs: *default-storage

    mc:
        command: mc
        plugs: *default-storage-net

    mcdiff:
        command: mcdiff
        plugs: *default-storage-net

    mcedit:
        command: mcedit
        plugs: *default-storage-net

    mcview:
        command: mcview
        plugs: *default-storage-net

    pastebinit:
        command: pastebinit
        plugs: *default-storage-net

    curl:
        command: curl
        plugs: *default-storage-net

    lsusb:
        command: lsusb
        plugs: [ raw-usb ]

    usb-devices:
        command: usb-devices
        plugs: [ raw-usb ]

    usbhid-dump:
        command: usbhid-dump
        plugs: [ raw-usb ]

    cppfilt:
        command: c++filt
        plugs: *default-storage

    elfedit:
        command: elfedit
        plugs: *default-storage

    readelf:
        command: readelf
        plugs: *default-storage

    ld:
        command: ld
        plugs: *default-storage

    ld-bfd:
        command: ld.bfd
        plugs: *default-storage

    strings:
        command: strings
        plugs: *default-storage

    size:
        command: size
        plugs: *default-storage

    strip:
        command: strip
        plugs: *default-storage

    objcopy:
        command: objcopy
        plugs: *default-storage

    objdump:
        command: objdump
        plugs: *default-storage

    addr2line:
        command: addr2line
        plugs: *default-storage

    dwp:
        command: dwp
        plugs: *default-storage

    as:
        command: as
        plugs: *default-storage

    ar:
        command: ar
        plugs: *default-storage

    gold:
        command: gold
        plugs: *default-storage

    ld-gold:
        command: ld.gold
        plugs: *default-storage

    nm:
        command: nm
        plugs: *default-storage

    gprof:
        command: gprof
        plugs: [ home, process-control, system-observe, mount-observe,hardware-observe, system-trace, physical-memory-control ]

    ranlib:
        command: ranlib
        plugs: *default-storage

    set-path:
        command: bin/set-path
        plugs: *default-storage

    screen:
        command: screen
        plugs: [ home, network, hardware-observe, serial-port, raw-usb ]

    tree:
        command: tree
        plugs: *default-storage

    zip:
        command: zip
        plugs: *default-storage

    unzip:
        command: unzip
        plugs: *default-storage

    vim:
        command: vim.basic
        plugs: *default-storage

    vim-tiny:
        command: vim.tiny
        plugs: *default-storage

    vimdiff:
        command: vim.basic -d
        plugs: *default-storage

    iotop:
        command: iotop
        plugs: &default-system [home, process-control, system-observe, mount-observe,hardware-observe,framebuffer, physical-memory-control, raw-usb, removable-media, system-trace]

    lsof:
        command: lsof
        plugs: *default-system

    hdparm:
        command: hdparm
        plugs: &default-hw [home, system-observe, mount-observe, hardware-observe, removable-media]

    rhash:
        command: rhash
        plugs: &default-hash [home, removable-media, hardware-random-control ]

    gost-hash:
        command: gost-hash
        plugs: *default-hash

    has160-hash:
        command: has160-hash
        plugs: *default-hash

    sfv-hash:
        command: sfv-hash
        plugs: *default-hash

    tiger-hash:
        command: tiger-hash
        plugs: *default-hash

    tth-hash:
        command: tth-hash
        plugs: *default-hash

    whirlpool-hash:
        command: whirlpool-hash
        plugs: *default-hash

    clean-journalctl:
        command: journalctl --vacuum-time=1seconds
        plugs: *default-system

    i2cset:
        command: usr/sbin/i2cset
        plugs: *default-hw

    i2cdump:
        command: usr/sbin/i2cdump
        plugs: *default-hw

    i2cdetect:
        command: usr/sbin/i2cdetect
        plugs: *default-hw

    i2cget:
        command: usr/sbin/i2cget
        plugs: *default-hw

    cryptsetup:
        command: sbin/cryptsetup
        plugs: *default-hw

    veritysetup:
        command: sbin/veritysetup
        plugs: *default-hw

    cryptsetup-reencrypt:
        command: sbin/cryptsetup-reencrypt
        plugs: *default-hw

    luksformat:
        command: usr/sbin/luksformat
        plugs: *default-hw

    dmsetup:
        command: sbin/dmsetup
        plugs: *default-hw

    convert-dtsv0:
        command: usr/bin/convert-dtsv0
        plugs: *default-hw

    dtdiff:
        command: usr/bin/dtdiff
        plugs: *default-hw

    fdtput:
        command: usr/bin/fdtput
        plugs: *default-hw

    dtc:
        command: usr/bin/dtc
        plugs: *default-hw

    fdtdump:
        command: usr/bin/fdtdump
        plugs: *default-hw

    fdtget:
        command: usr/bin/fdtget
        plugs: *default-hw

    strace:
        command: usr/bin/strace
        plugs:
            - log-observe

    rsync:
        command: usr/bin/rsync
        plugs:
            - home
            - removable-media
            - optical-drive

    iperf3:
        command: usr/bin/iperf3
        plugs: &default-net [ home, network, network-bind, network-control, network-observe, network-setup-control, network-setup-observe ]

    netstat:
        command: bin/netstat
        plugs: *default-net

    arp:
        command: usr/sbin/arp
        plugs: *default-net

    nameif:
        command: sbin/nameif
        plugs: *default-net

    ipmaddr:
        command: sbin/ipmaddr
        plugs: *default-net

    plipconfig:
        command: sbin/plipconfig
        plugs: *default-net

    ifconfig:
        command: sbin/ifconfig
        plugs: *default-net

    route:
        command: sbin/route
        plugs: *default-net

    mii-tool:
        command: sbin/mii-tool
        plugs: *default-net

    iptunnel:
        command: sbin/iptunnel
        plugs: *default-net

    rarp:
        command: sbin/rarp
        plugs: *default-net

    slattach:
        command: sbin/slattach
        plugs: *default-net

    ethtool:
        command: sbin/ethtool
        plugs: *default-net

    fuser:
        command: bin/fuser
        plugs: *default-system

    killall:
        command: usr/bin/killall
        plugs: *default-system

    pstree:
        command: usr/bin/pstree
        plugs: *default-system

    prtstat:
        command: usr/bin/prtstat
        plugs: *default-system

    peekfd:
        command: usr/bin/peekfd
        plugs: *default-system

parts:
    tools:
        source: scripts
        plugin: dump
        stage-packages:
          - wget
          - nano
          - silversearcher-ag
          - pastebinit
          - curl
          - binutils
          - screen
          - tree
          - zip
          - unzip
          - vim
          - vim-tiny
          - vim-common
          - vim-runtime
          - lsof
          - iotop
          - hdparm
          - rhash
          - ethtool
          - i2c-tools
          - cryptsetup-bin
          - libgpm2
          - dmsetup
          - device-tree-compiler
          - strace
          - rsync
          - iperf3
          - net-tools
          - psmisc
        filesets:
          fat:
            - -usr/lib/gcc
            - -usr/share/vim
        stage:
            - $fat
        prime:
            - $fat

    mc:
        source: https://github.com/MidnightCommander/mc.git
        plugin: autotools
        configflags:
            - --prefix=/snap/toolbox/current/usr 
            - --sysconfdir=/var/snap/toolbox/common/etc
            - --without-x
        build-packages:
            - libglib2.0-dev
            - libslang2-dev
            - gettext
        override-build: |
            snapcraftctl build
            mv $SNAPCRAFT_PART_INSTALL/snap/toolbox/current/usr $SNAPCRAFT_PART_INSTALL/
            rm -rf $SNAPCRAFT_PART_INSTALL/snap
            mv $SNAPCRAFT_PART_INSTALL/var/snap/toolbox/common/etc $SNAPCRAFT_PART_INSTALL/
            rm -rf $SNAPCRAFT_PART_INSTALL/var

    usbutils:
        source: https://github.com/gregkh/usbutils.git
        plugin: autotools
        build-packages:
            - libusb-1.0-0-dev
            - zlib1g
            - gawk
            - pkg-config
            - libudev-dev
        stage-packages: [libusb-1.0-0]
        configflags:
            - --prefix=/usr
            - --libdir=/usr/lib
            - --localstatedir=/var/snap/toolbox/common/
        override-pull: |
            snapcraftctl pull
            git submodule init
            git submodule update
            autoreconf --install --symlink
