name: toolbox
version: "0.4.9"
summary: set of usefull shell tools
description: |
 set of usefull shell tools

confinement: strict
grade: stable
architectures:
    - build-on: armhf
    - build-on: arm64
    - build-on: i386
    - build-on: amd64
    - build-on: ppc64el

environment:
    PATH:            $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
    LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}

apps:
    help:
        command: bin/toolbox-help
        adapter: none

    nano:
        command: bin/nano
        adapter: none
        plugs: &default-storage [home, removable-media]

    wget:
        command: usr/bin/wget
        adapter: none
        plugs: &default-storage-net [home, removable-media, network]
        completer: usr/share/bash-completion/completions/wget

    ag:
        command: usr/bin/ag
        adapter: none
        plugs: *default-storage
        completer: usr/share/bash-completion/completions/ag

    mc:
        command: usr/bin/mc
        adapter: none
        plugs: *default-storage-net
        completer: usr/share/bash-completion/completions/mc

    mcdiff:
        command: usr/bin/mcdiff
        adapter: none
        plugs: *default-storage-net

    mcedit:
        command: usr/bin/mcedit
        adapter: none
        plugs: *default-storage-net

    mcview:
        command: usr/bin/mcview
        adapter: none
        plugs: *default-storage-net

    pastebinit:
        command: usr/bin/pastebinit
        adapter: none
        plugs: *default-storage-net

    curl:
        command: usr/bin/curl
        adapter: none
        plugs: *default-storage-net
        completer: usr/share/bash-completion/completions/curl

    lsusb:
        command: usr/bin/lsusb
        adapter: none
        plugs: [ raw-usb ]

    usb-devices:
        command: usr/bin/usb-devices
        adapter: none
        plugs: [ raw-usb ]

    usbhid-dump:
        command: usr/bin/usbhid-dump
        adapter: none
        plugs: [ raw-usb ]

    cppfilt:
        command: usr/bin/c++filt
        plugs: *default-storage

    elfedit:
        command: usr/bin/elfedit
        adapter: none
        plugs: *default-storage

    readelf:
        command: usr/bin/readelf
        adapter: none
        plugs: *default-storage

    ld:
        command: usr/bin/ld
        adapter: none
        plugs: *default-storage

    ld-bfd:
        command: usr/bin/ld.bfd
        adapter: none
        plugs: *default-storage

    strings:
        command: usr/bin/strings
        adapter: none
        plugs: *default-storage
        completer: usr/share/bash-completion/completions/strings

    size:
        command: usr/bin/size
        adapter: none
        plugs: *default-storage

    strip:
        command: usr/bin/strip
        adapter: none
        plugs: *default-storage

    objcopy:
        command: usr/bin/objcopy
        adapter: none
        plugs: *default-storage

    objdump:
        command: usr/bin/objdump
        adapter: none
        plugs: *default-storage

    addr2line:
        command: usr/bin/addr2line
        adapter: none
        plugs: *default-storage

    dwp:
        command: usr/bin/dwp
        adapter: none
        plugs: *default-storage

    as:
        command: usr/bin/as
        adapter: none
        plugs: *default-storage

    ar:
        command: usr/bin/ar
        adapter: none
        plugs: *default-storage

    gold:
        command: usr/bin/gold
        adapter: none
        plugs: *default-storage

    ld-gold:
        command: usr/bin/ld.gold
        adapter: none
        plugs: *default-storage

    nm:
        command: usr/bin/nm
        adapter: none
        plugs: *default-storage

    gprof:
        command: usr/bin/gprof
        adapter: none
        plugs: [ home, process-control, system-observe, mount-observe,hardware-observe, system-trace, physical-memory-control ]
        completer: usr/share/bash-completion/completions/gprof

    ranlib:
        command: usr/bin/ranlib
        adapter: none
        plugs: *default-storage

    screen:
        command: usr/bin/screen
        adapter: none
        plugs: [ home, network, hardware-observe, serial-port, raw-usb ]
        completer: usr/share/bash-completion/completions/screen

    tree:
        command: usr/bin/tree
        adapter: none
        plugs: *default-storage

    zip:
        command: usr/bin/zip
        adapter: none
        plugs: *default-storage

    unzip:
        command: usr/bin/unzip
        adapter: none
        plugs: *default-storage

    vim:
        command: usr/bin/vim.basic
        adapter: none
        plugs: *default-storage

    vim-tiny:
        command: usr/bin/vim.tiny
        adapter: none
        plugs: *default-storage

    vimdiff:
        command: usr/bin/vim.basic -d
        adapter: none
        plugs: *default-storage

    iotop:
        command: usr/sbin/iotop
        adapter: none
        plugs: &default-system [home, process-control, system-observe, mount-observe,hardware-observe,framebuffer, physical-memory-control, raw-usb, removable-media, system-trace]

    lsof:
        command: usr/bin/lsof
        adapter: none
        plugs: *default-system
        completer: usr/share/bash-completion/completions/lsof

    hdparm:
        command: sbin/hdparm
        adapter: none
        plugs: &default-hw [home, system-observe, mount-observe, hardware-observe, removable-media]

    rhash:
        command: usr/bin/rhash
        adapter: none
        plugs: &default-hash [home, removable-media, hardware-random-control ]

    gost-hash:
        command: usr/bin/gost-hash
        adapter: none
        plugs: *default-hash

    has160-hash:
        command: usr/bin/has160-hash
        adapter: none
        plugs: *default-hash

    sfv-hash:
        command: usr/bin/sfv-hash
        adapter: none
        plugs: *default-hash

    tiger-hash:
        command: usr/bin/tiger-hash
        adapter: none
        plugs: *default-hash

    tth-hash:
        command: usr/bin/tth-hash
        adapter: none
        plugs: *default-hash

    whirlpool-hash:
        command: usr/bin/whirlpool-hash
        adapter: none
        plugs: *default-hash

    clean-journalctl:
        command: journalctl --vacuum-time=1seconds
        plugs:
            - log-observe

    i2cset:
        command: usr/sbin/i2cset
        adapter: none
        plugs: *default-hw

    i2cdump:
        command: usr/sbin/i2cdump
        adapter: none
        plugs: *default-hw

    i2cdetect:
        command: usr/sbin/i2cdetect
        adapter: none
        plugs: *default-hw

    i2cget:
        command: usr/sbin/i2cget
        adapter: none
        plugs: *default-hw

    cryptsetup:
        command: sbin/cryptsetup
        adapter: none
        plugs: *default-hw
        completer: usr/share/bash-completion/completions/cryptsetup

    veritysetup:
        command: sbin/veritysetup
        adapter: none
        plugs: *default-hw

    cryptsetup-reencrypt:
        command: sbin/cryptsetup-reencrypt
        adapter: none
        plugs: *default-hw

    luksformat:
        command: usr/sbin/luksformat
        adapter: none
        plugs: *default-hw

    dmsetup:
        command: sbin/dmsetup
        adapter: none
        plugs: *default-hw

    convert-dtsv0:
        command: usr/bin/convert-dtsv0
        adapter: none
        plugs: *default-hw

    dtdiff:
        command: usr/bin/dtdiff
        adapter: none
        plugs: *default-hw

    fdtput:
        command: usr/bin/fdtput
        adapter: none
        plugs: *default-hw

    dtc:
        command: usr/bin/dtc
        adapter: none
        plugs: *default-hw

    fdtdump:
        command: usr/bin/fdtdump
        adapter: none
        plugs: *default-hw

    fdtget:
        command: usr/bin/fdtget
        adapter: none
        plugs: *default-hw

    strace:
        command: usr/bin/strace
        adapter: none
        plugs:
            - log-observe
        completer: usr/share/bash-completion/completions/strace

    rsync:
        command: usr/bin/rsync
        adapter: none
        plugs:
            - home
            - removable-media
            - optical-drive
        completer: usr/share/bash-completion/completions/rsync

    iperf3:
        command: usr/bin/iperf3
        adapter: none
        plugs: &default-net [ home, network, network-bind, network-control, network-observe, network-setup-control, network-setup-observe ]

    netstat:
        command: bin/netstat
        adapter: none
        plugs: *default-net

    arp:
        command: usr/sbin/arp
        adapter: none
        plugs: *default-net

    nameif:
        command: sbin/nameif
        adapter: none
        plugs: *default-net

    ipmaddr:
        command: sbin/ipmaddr
        adapter: none
        plugs: *default-net

    plipconfig:
        command: sbin/plipconfig
        adapter: none
        plugs: *default-net

    ifconfig:
        command: sbin/ifconfig
        adapter: none
        plugs: *default-net

    route:
        command: sbin/route
        adapter: none
        plugs: *default-net
        completer: usr/share/bash-completion/completions/route

    mii-tool:
        command: sbin/mii-tool
        adapter: none
        plugs: *default-net
        completer: usr/share/bash-completion/completions/mii-tool

    iptunnel:
        command: sbin/iptunnel
        adapter: none
        plugs: *default-net

    rarp:
        command: sbin/rarp
        adapter: none
        plugs: *default-net

    slattach:
        command: sbin/slattach
        adapter: none
        plugs: *default-net

    ethtool:
        command: sbin/ethtool
        adapter: none
        plugs: *default-net

    fuser:
        command: bin/fuser
        adapter: none
        plugs: *default-system

    killall:
        command: usr/bin/killall
        adapter: none
        plugs: *default-system
        completer: usr/share/bash-completion/completions/killall

    pstree:
        command: usr/bin/pstree
        adapter: none
        plugs: *default-system

    prtstat:
        command: usr/bin/prtstat
        adapter: none
        plugs: *default-system

    peekfd:
        command: usr/bin/peekfd
        adapter: none
        plugs: *default-system

    htop:
        command: usr/bin/htop
        adapter: none
        plugs: *default-system
        completer: usr/share/bash-completion/completions/htop

    devmem2:
        command: usr/bin/devmem2
        adapter: none
        plugs: *default-system

    busybox:
        command: bin/busybox
        adapter: none
        plugs: *default-system

    lshw:
        command: usr/bin/lshw
        adapter: none
        plugs: *default-system

    lspci:
        command: usr/bin/lspci
        adapter: none
        plugs: *default-system

    pcimodules:
        command: usr/bin/pcimodules
        adapter: none
        plugs: *default-system

    setpci:
        command: usr/bin/setpci
        adapter: none
        plugs: *default-system

    resty:
        command: bin/bash --init-file $SNAP/usr/bin/resty
        adapter: none
        plugs: *default-system

    http:
        command: usr/bin/http
        adapter: none
        plugs: *default-system
        completer: usr/share/bash-completion/completions/httpie

    dig:
        command: usr/bin/dig
        adapter: none
        plugs: *default-net

    nsupdate:
        command: usr/bin/nsupdate
        adapter: none
        plugs: *default-net

    nslookup:
        command: usr/bin/nslookup
        adapter: none
        plugs: *default-net

    jq:
        command: usr/bin/jq
        adapter: none
        plugs: *default-net

parts:
    tools:
        source: scripts
        plugin: dump
        stage-packages:
          - bash-completion
          - wget
          - nano
          - silversearcher-ag
          - pastebinit
          - curl
          - binutils
          - screen
          - tree
          - zip
          - unzip
          - vim
          - vim-tiny
          - vim-common
          - vim-runtime
          - lsof
          - iotop
          - hdparm
          - rhash
          - ethtool
          - i2c-tools
          - cryptsetup-bin
          - libgpm2
          - dmsetup
          - device-tree-compiler
          - strace
          - rsync
          - iperf3
          - net-tools
          - psmisc
          - libdb5.3
          - htop
          - devmem2
          - busybox-static
          - lshw
          - pciutils
          - bash
          - httpie
          - dnsutils
          - util-linux
          - jq
          - libjq1
          - libonig4
        filesets:
          fat:
            - -usr/lib/gcc
            - -usr/share/vim
        stage:
            - $fat
        prime:
            - $fat
        override-build: |
            snapcraftctl build
            echo "Checking if usr/bin/peekfd exists"
            # interestingly on arm64 there is no usr/bin/peekfd, account for this
            if [ ! -f ${SNAPCRAFT_PART_INSTALL}/usr/bin/peekfd ]; then
                echo "adding stub for usr/bin/peekfd"
                echo "#!/bin/bash" > ${SNAPCRAFT_PART_INSTALL}/usr/bin/peekfd
                echo "echo 'peekfd is not supported on arm64'" >> ${SNAPCRAFT_PART_INSTALL}/usr/bin/peekfd
                chmod +x ${SNAPCRAFT_PART_INSTALL}/usr/bin/peekfd
            fi

    mc:
        source: https://github.com/MidnightCommander/mc.git
        plugin: autotools
        configflags:
            - --prefix=/snap/toolbox/current/usr
            - --sysconfdir=/var/snap/toolbox/common/etc
            - --without-x
        build-packages:
            - libglib2.0-dev
            - libslang2-dev
            - gettext
        override-build: |
            snapcraftctl build
            mv ${SNAPCRAFT_PART_INSTALL}/snap/toolbox/current/usr ${SNAPCRAFT_PART_INSTALL}/
            rm -rf ${SNAPCRAFT_PART_INSTALL}/snap
            mv ${SNAPCRAFT_PART_INSTALL}/var/snap/toolbox/common/etc ${SNAPCRAFT_PART_INSTALL}/
            rm -rf ${SNAPCRAFT_PART_INSTALL}/var

    usbutils:
        source: https://github.com/gregkh/usbutils.git
        plugin: autotools
        build-packages:
            - libusb-1.0-0-dev
            - zlib1g
            - gawk
            - pkg-config
            - libudev-dev
        stage-packages: [libusb-1.0-0]
        configflags:
            - --prefix=/usr
            - --libdir=/usr/lib
            - --localstatedir=/var/snap/toolbox/common/
        override-pull: |
            snapcraftctl pull
            git submodule init
            git submodule update
            autoreconf --install --symlink

    resty:
        plugin: nil
        source: https://github.com/micha/resty.git
        build-packages:
            - curl
        override-build: |
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
            cp pp pypp ${SNAPCRAFT_PART_INSTALL}/usr/bin
            cp resty ${SNAPCRAFT_PART_INSTALL}/usr/bin
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/bash-completion/completions/
            curl -o ${SNAPCRAFT_PART_INSTALL}/usr/share/bash-completion/completions/httpie https://raw.githubusercontent.com/jakubroztocil/httpie/master/extras/httpie-completion.bash
